from .segformer_head import SegFormerHead
from .fcn_head import FCNHead
from .psp_head import PSPHead
from .ham_head import LightHamHead
from .uper_head import UPerHead
from .ea_head import EAHead
from .cc_head import CCHead
from .da_head import DAHead
from .aspp_head import ASPPHead
from .sep_aspp_head import DepthwiseSeparableASPPHead
from .point_head import PointHead
from .fpn_head import FPNHead
